import type { ChangeEventType } from './Filter.types'

export function getFilterValueByInput(event: ChangeEventType): string {
  if (event.target.value?.toLocaleLowerCase() === 'beliebig') return 'all'
  return event.target.value
}

export function getAllBrands() {
  return [
    'Beliebig',
    'Audi',
    'BMW',
    'Mercedes-Benz',
    'Volkswagen',
    'Porsche',
    'Opel',
    'Ford',
    'Skoda',
    'Seat',
    'Volvo',
    'Mini',
    'Land Rover',
    'Jaguar',
    'Fiat',
    'Alfa Romeo',
    'Maserati',
    'Lamborghini',
    'Ferrari',
    'Aston Martin',
    'Rolls-Royce',
    'Bentley',
    'Bugatti',
    'Peugeot',
    'Citroën',
    'Renault',
    'Dacia',
    'Nissan',
    'Mitsubishi',
    'Toyota',
    'Lexus',
    'Honda',
    'Mazda',
    'Subaru',
    'Suzuki',
    'Hyundai',
    'Kia',
    'Genesis',
    'Chevrolet',
    'Cadillac',
    'Jeep',
    'Dodge',
    'Chrysler',
    'GMC',
    'Tesla',
    'Rivian',
    'Polestar',
    'Lynk & Co',
    'Byton',
    'Borgward',
    'Wiesmann',
  ]
}
